#ifndef PROCEDURAL_SHADER_FRAMEWORK_H
#define PROCEDURAL_SHADER_FRAMEWORK_H

#include "global_variables.ush"
#include "helper_functions.ush"
#include "sdf_functions.ush"
#include "util_functions.ush"
#include "animation_functions.ush"
#include "camera_functions.ush"
#include "lighting_functions.ush"
#include "material_functions.ush"
#include "noise_functions.ush"
#include "water_functions.ush"
#include "tween_functions.ush"

#endif