// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

float resolutionX;
float _Time;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    
    float x = id.x / resolutionX;
    float y = id.y / resolutionX;
    // Result[id.xy] = float4(x, y, 0.0, 0.0);

    // Result[id.xy] = float4(id.x & id.y, (id.x & 31) / 31.0, (id.y & 31) / 31.0, 0.0);
    
    float2 p = float2(id.x, id.y) * 0.1;
    float r = length(p);
    Result[id.xy] = float4(
    0.5 + 0.5 * sin(r - _Time),
    frac((id.x ^ id.y) * 0.05 + _Time * 0.2),
    0.5 + 0.5 * cos(p.x * 2 + _Time),
    1.0
);
}
