#include "ProceduralShaderFramework/procedural_shader.ush"

float3 Render()
{
    float sdfIndex = 0;
    // float3 baseColor, float3 specularColor, float specularStrength, float shininess, float roughness, float metallic, float rimPower, float fakeSpecularPower, float3 fakeSpecularColor, float ior, float refractionStrength, float3 refractionTint
    MaterialParams sphereColor = makeMaterial(float3(0.728184, 1.0, 0.014647), float3(1.0, 0, 0), 1.0, 32, 0.5, 0.0, 0.1, 32, float3(0.728184, 1.0, 0.014647), 1.45, 0.0, float3(1, 1, 1));
    addSphere(sdfIndex, float(-4.5, 0, 0), 1.5, float3(0.0, 0.0, 0.0), 0, sphereColor);
    
}