site_name: Shader Documentation

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expansion
    - navigation.path
    - navigation.top
    - content.code.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search

markdown_extensions:
  - toc:
      toc_depth : "1-1"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.mark
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

  #-- - Shaders:
     # - Overview: shaders/shaderPage.md
     # - Animation:
      #    - TIE Fighter: shaders/animation/tie_fighter.md
      # You can add more categories like this:
      # - Noise:
      #     - Cloud FBM: shaders/noise/cloud_fbm.md -->
  - Godot: engines/godot.md
  - Unity:
    - Integration: engines/unity.md
    - Global Variables: engines/unity/globalVariables.md
    - Helper Functions: engines/unity/helperFunctions.md
    - Uniforms and C#: engines/unity/uniformsAndCs.md
    - Custom HLSL:
      - Camera:
        - Camera Matrix: engines/unity/camera/cameraMatrix.md
        - Camera Rotation: engines/unity/camera/cameraRotation.md
        - Camera Translation: engines/unity/camera/cameraBackAndForth.md
        - Camera Mouse-Based Movement: engines/unity/camera/mouseBasedMovement.md
      - Animation: 
        - Orbit Object Around Point: engines/unity/animations/orbitObject.md
        - Shake Object: engines/unity/animations/shakeObject.md
      - Basics: engines/unity.md
      - Water Environment: engines/unity.md
      - Lighting: engines/unity.md
      - SDFs: engines/unity.md
    - Tutorials:
      - Christmas Tree: engines/unity.md
      - Safety Buoy: engines/unity.md
  - Unreal Engine: engines/unreal.md
    