site_name: Shader Documentation

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expansion
    - navigation.path
    - navigation.top
    - content.code.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search

markdown_extensions:
  - toc:
      toc_depth : "1-1"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.mark
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - style.css

nav:
  - Home: index.md

  #-- - Shaders:
     # - Overview: shaders/shaderPage.md
     # - Animation:
      #    - TIE Fighter: shaders/animation/tie_fighter.md
      # You can add more categories like this:
      # - Noise:
      #     - Cloud FBM: shaders/noise/cloud_fbm.md -->
      
  - Shaders: shaders/shaderPage.md
  - Godot: engines/godot.md
  - Unity:
    - Overview: engines/unity.md
    - Global Variables: engines/unity/globalVariables.md
    - Helper Functions: engines/unity/helperFunctions.md
    - Uniforms and C#: engines/unity/uniformsAndCs.md
    - Custom HLSL:
      - Basics: 
        - Fragment Coordinates: engines/unity/basics/fragCoords.md
        - Combine Color: engines/unity/basics/combineColor.md
        - Minimum: engines/unity/basics/minimum.md
      - Camera:
        - Camera Matrix: engines/unity/camera/cameraMatrix.md
        - Rotation: engines/unity/camera/cameraRotation.md
        - Back And Forth: engines/unity/camera/cameraBackAndForth.md
        - Mouse-Based Rotation: engines/unity/camera/mouseBasedMovement.md
      - SDFs: 
        - General Information: engines/unity/sdfs/generalInformation.md
        - Sphere: engines/unity/sdfs/sphere.md
        - RoundBox: engines/unity/sdfs/cube.md
        - Torus: engines/unity/sdfs/torus.md
        - Ellipsoid: engines/unity/sdfs/ellipsoid.md
        - Hexagonal Prism: engines/unity/sdfs/hexPrism.md
        - Octahedron: engines/unity/sdfs/octahedron.md
        - Dolphin: engines/unity/sdfs/dolphin.md
      - Environments: 
        - Water Surface: engines/unity/water/waterSurface.md
        - Water Height: engines/unity/water/waterHeight.md
        - Water Normal: engines/unity/water/waterNormal.md
      - Lighting: engines/unity.md
      - Animation: 
        - Orbit Object Around Point: engines/unity/animations/orbitObject.md
        - Shake Object: engines/unity/animations/shakeObject.md
        - Tweening: engines/unity/animations/tweening.md
        - Cycle Color: engines/unity/animations/colorAnimation.md
      - Lighting:
        - Sunrise Light: engines/unity/lighting/sunriseLight.md 
    - Tutorials:
      - Christmas Tree: engines/unity.md
      - Safety Buoy: engines/unity.md
  - Unreal Engine: engines/unreal.md
    