site_name: Shader Documentation

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expansion
    - navigation.path
    - navigation.top
    - content.code.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search

markdown_extensions:
  - toc:
      toc_depth: "1-1"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.mark
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2025 TU DRESDEN FAKULTÄT INFORMATIK
extra:
  #generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://tu-dresden.de/ing/informatik

    - icon: fontawesome/brands/github
      link: https://github.com/friedaxvictoria/procedural_shader_framework.git

extra_css:
  - style.css

nav:
  - Home: index.md

  #-- - Shaders:
  # - Overview: shaders/shaderPage.md
  # - Animation:
  #    - TIE Fighter: shaders/animation/tie_fighter.md
  # You can add more categories like this:
  # - Noise:
  #     - Cloud FBM: shaders/noise/cloud_fbm.md -->

  - Shaders: shaders/shaderPage.md
  - Godot: 
    - Shader Flow Pipeline: 
      - Overall Structure: engines/godot.md
      - Framework Workflow: engines/godot/structure.md
    - Global Variables: engines/godot/globalVariables.md
    - Helper Functions: engines/godot/helperFunction.md
    - GD Script: engines/godot/gdScript.md
    - GD Shader Include: engines/godot/gdShaderInclude.md
    - Main Fragment Shader: engines/godot/mainFragmentShader.md
    - User Guide: engines/godot/shaderFlow.md
    - Tutorial: engines/godot/tutorials.md

  - Unity:
      - Overview: engines/unity.md
      - Global Variables: engines/unity/globalVariables.md
      - Helper Functions: engines/unity/helperFunctions.md
      - Uniforms and C#: engines/unity/uniformsAndCs.md
      - The Integration:
          - Basics:
              - Fragment Coordinates: engines/unity/basics/fragCoords.md
              - Combine Color: engines/unity/basics/combineColor.md
              - Minimum: engines/unity/basics/minimum.md
          - Camera:
              - Camera Matrix: engines/unity/camera/cameraMatrix.md
              - Rotation: engines/unity/camera/cameraRotation.md
              - Back And Forth: engines/unity/camera/cameraBackAndForth.md
              - Mouse-Based Rotation: engines/unity/camera/mouseBasedMovement.md
          - SDFs:
              - General Information: engines/unity/sdfs/generalInformation.md
              - Sphere: engines/unity/sdfs/sphere.md
              - RoundBox: engines/unity/sdfs/cube.md
              - Torus: engines/unity/sdfs/torus.md
              - Ellipsoid: engines/unity/sdfs/ellipsoid.md
              - Hexagonal Prism: engines/unity/sdfs/hexPrism.md
              - Octahedron: engines/unity/sdfs/octahedron.md
              - Dolphin: engines/unity/sdfs/dolphin.md
              - SDF Raymarching: engines/unity/sdfs/raymarching.md
          - Environments:
              - Water Surface: engines/unity/water/waterSurface.md
              - Water Height: engines/unity/water/waterHeight.md
              - Water Normal: engines/unity/water/waterNormal.md
          - Animations:
              - General Information: engines/unity/animations/generalInformation.md
              - Orbit Object Around Point: engines/unity/animations/orbitObject.md
              - Shake Object: engines/unity/animations/shakeObject.md
              - Tweening: engines/unity/animations/tweening.md
              - Cycle Color: engines/unity/animations/colorAnimation.md
          - Lighting:
              - General Information: engines/unity/lighting/generalInformation.md
              - Sunrise: engines/unity/lighting/sunriseLight.md
              - Point Light: engines/unity/lighting/pointLight.md
              - Lambertian Lighting: engines/unity/lighting/lambLight.md
              - Blinn Phong Lighting: engines/unity/lighting/blinnPhongLight.md
              - Toon Lighting: engines/unity/lighting/toonLight.md
              - Rim Lighting: engines/unity/lighting/rimLight.md
              - Soft Subsurface Scattering: engines/unity/lighting/softSubsurfaceScattering.md
              - Fresnel Lighting: engines/unity/lighting/fresnelLight.md
              - UV Gradient Lighting: engines/unity/lighting/uvGradientLight.md
              - UV Anisotropic Lighting: engines/unity/lighting/uvAnisotropicLight.md
      - Tutorials:
          - Christmas Tree: engines/unity/tutorials/christmasTree.md
          - Safety Buoy: engines/unity/tutorials/safetyBuoy.md
          - Elevator: engines/unity/tutorials/elevator.md
          - Car: engines/unity/tutorials/car.md
          - Shrine: engines/unity/tutorials/shrine.md
  - Unreal Engine:
    - Overview: engines/unreal.md
    - Global Variables: engines/unreal/globalVariables.md
    - Helper Functions: engines/unreal/helperFunctions.md
    - ShaderPlayground: engines/unreal/basics/ShaderPlayground.md
    - The Integration:
      - Utility: 
        - Fragment Coordinates: engines/unreal/utils/fragCoords.md
        - Combine Color: engines/unreal/utils/combineColor.md
        - Minimum: engines/unreal/utils/minimum.md
      - Camera:
        - Camera Matrix: engines/unreal/camera/cameraMatrix.md
        - Rotation: engines/unreal/camera/cameraRotation.md
        - Back And Forth: engines/unreal/camera/cameraBackAndForth.md
        - Mouse-Based Rotation: engines/unreal/camera/mouseBasedMovement.md
      - SDFs: 
        - General Information: engines/unreal/sdfs/generalInformation.md
        - Sphere: engines/unreal/sdfs/sphere.md
        - RoundBox: engines/unreal/sdfs/cube.md
        - Torus: engines/unreal/sdfs/torus.md
        - Ellipsoid: engines/unreal/sdfs/ellipsoid.md
        - Hexagonal Prism: engines/unreal/sdfs/hexPrism.md
        - Octahedron: engines/unreal/sdfs/octahedron.md
        - Dolphin: engines/unreal/sdfs/dolphin.md
        - SDF Raymarching: engines/unreal/sdfs/raymarching.md
      - Environments: 
        - Water Surface: engines/unreal/water/waterSurface.md
        - Water Height: engines/unreal/water/waterHeight.md
        - Water Normal: engines/unreal/water/waterNormal.md
      - Animation: 
        - Orbit Object Around Point: engines/unreal/animations/orbitObject.md
        - Shake Object: engines/unreal/animations/shakeObject.md
        - Tweening: engines/unreal/animations/tweening.md
        - Cycle Color: engines/unreal/animations/colorAnimation.md
      - Lighting:
        - General Information: engines/unreal/lighting/generalInformation.md
        - Sunrise: engines/unreal/lighting/sunriseLight.md 
        - Point Light: engines/unreal/lighting/pointLight.md
        - Lambertian Lighting: engines/unreal/lighting/lambLight.md
        - Blinn Phong Lighting: engines/unreal/lighting/blinnPhongLight.md
        - Toon Lighting: engines/unreal/lighting/toonLight.md
        - Rim Lighting: engines/unreal/lighting/rimLight.md
        - Soft Subsurface Scattering: engines/unreal/lighting/softSubsurfaceScattering.md
        - Fresnel Lighting: engines/unreal/lighting/fresnelLight.md
        - UV Gradient Lighting: engines/unreal/lighting/uvGradientLight.md
        - UV Anisotropic Lighting: engines/unreal/lighting/uvAnisotropicLight.md
    - Tutorials:
      - Christmas Tree: engines/unreal/tutorials/christmasTree.md
      - Christmas Tree - HLSL: engines/unreal/tutorials/christmasTree_hlsl.md
