site_name: Shader Documentation

theme:
  name: material
  #custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.code.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.footer
    
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.mark
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md

  #-- - Shaders:
     # - Overview: shaders/shaderPage.md
     # - Animation:
      #    - TIE Fighter: shaders/animation/tie_fighter.md
      # You can add more categories like this:
      # - Noise:
      #     - Cloud FBM: shaders/noise/cloud_fbm.md -->
  - Engines:
    - Godot: engines/godot.md
    - Unity: engines/unity.md
    - Unreal Engine: engines/unreal.md
    